# Generated by Django 3.2.7 on 2022-11-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_auto_20221108_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
