# Generated by Django 3.2.7 on 2022-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='gravatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
