# Generated by Django 3.2.7 on 2022-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0006_auto_20221110_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
