# Generated by Django 3.2.7 on 2022-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0010_alter_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='gravatar_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
